# Onur Zobi - 03/2019
#
# DP
Write-Host "
   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM   
  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMM       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMM       MMMMMMMMMMM        MMMMMMMMMMMMMMMM
MMMMMMMMMMMMMM                      MMMM                    MMMMMMMMMMM
MMMMMMMMMMMM                        MMM                      MMMMMMMMMM
MMMMMMMMMMM       MMMMMMMMMM       MM        MMMMMMMMMM       MMMMMMMMM
MMMMMMMMMM       MMMMMMMMMMM       MM       MMMMMMMMMMM       MMMMMMMMM
MMMMMMMMMM       MMMMMMMMMMM       MM       MMMMMMMMMMM       MMMMMMMMM
MMMMMMMMM        MMMMMMMMMMM       MM       MMMMMMMMMMM       MMMMMMMMM
MMMMMMMM         MMMMMMMMMMM       MM       MMMMMMMMMMM       MMMMMMMMM
MMMMMMMM        MMMMMMMMMMM        MM      MMMMMMMMMMMM       MMMMMMMMM
MMMMMMMM        MMMMMMMMMMM       MM       MMMMMMMMMMMM       MMMMMMMMM
MMMMMMMM        MMMMMMMMMMM       MM       MMMMMMMMMMM        MMMMMMMMM
MMMMMMMM        MMMMMMMMMM        MM       MMMMMMMMMMM       MMMMMMMMMM
MMMMMMMM       MMMMMMMMMMM        MM       MMMMMMMMMMM       MMMMMMMMMM
MMMMMMMMM      MMMMMMMMMMM       MM        MMMMMMMMMM       MMMMMMMMMMM
MMMMMMMMM      MMMMMMMMMMM       MM        MMMMMMMMMM       MMMMMMMMMMM
MMMMMMMMM      MMMMMMMMMMM       MM       MMMMMMMMMMM      MMMMMMMMMMMM
MMMMMMMMMM                       MM                       MMMMMMMMMMMMM
MMMMMMMMMMMM                    MM                      MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        MMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 
   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM  
" -foregroundcolor Red -backgroundcolor White

if (Test-Path .\_TEMP ) {
    	Remove-Item -path .\_TEMP -recurse -force
    }
    
Write-Host Welcome! -foregroundcolor Magenta
Write-Host 

# Selection PDF, WEB, or ALL
Write-Host "1. Compile PDF"
Write-Host "2. Compile Website"
Write-Host "3. BOTH"
Write-Host 
$num1 = Read-Host "Make a selection"
Write-Host 

# Selection of Content
$list = Get-ChildItem -Path ./Contents -Attributes Directory

$k=1;
foreach ($file in $list) {
    Write-Host "$k. $file"
    $k++
}
Write-Host "$k. ALL"
Write-Host 
$num2 = Read-Host "Make a selection"
Write-Host 
Write-Host 

# Compile Selection
switch ( $num1 ){
	"1" {
		if($num2 -eq $k){
			foreach ($file in $list) {
				$folderName=$file.Name
				& (.\Resources\Compile_PDF.ps1)
			}
		} else{
			$folderName=$list[$num2-1].Name
			& (.\Resources\Compile_PDF.ps1)
		}
        break
	}

	"2" {
		if($num2 -eq $k){
			foreach ($file in $list) {
				$folderName=$file.Name
				& (.\Resources\Compile_WEB.ps1)
			}
		} else{
			$folderName=$list[$num2-1].Name
			& (.\Resources\Compile_WEB.ps1)
		}
		break
	}

	"3" {
		if($num2 -eq $k){
			foreach ($file in $list) {
				$folderName=$file.Name
				& (.\Resources\Compile_WEB.ps1)
				& (.\Resources\Compile_PDF.ps1)
			}
		} else{
			$folderName=$list[$num2-1].Name
			& (.\Resources\Compile_WEB.ps1)
			& (.\Resources\Compile_PDF.ps1)
		}
		break
	}
	default {return 0; break}
}